name: release
on:
  workflow_dispatch:

jobs:
  mac_build:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        brew install scons
        cp build/build_macos.sh .
        sudo chmod +x build_macos.sh
        ./build_macos.sh ci
        cd release
        tar -czf ../mac_release.tar.gz *
        cd ..
​      - ​name​: ​Upload App To Artifact
steps:
​        ​uses​: ​actions/upload-artifact@v4
​        ​with​:
​          ​path​: ​"mac_release.tar.gz"

  linux_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        sudo chmod +x build/build_linux.sh
        ./build/build_linux.sh ci
        cd release
        tar -czf ../linux_release.tar.gz *
        cd ..
​      - ​name​: ​Upload App To Artifact
steps:
​        ​uses​: ​actions/upload-artifact@v4
​        ​with​:
​          ​path​: ​"linux_release.tar.gz"

  android_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'gradle'
    - uses: nttld/setup-ndk@v1
      with:
        ndk-version: r25c
        link-to-sdk: true
        add-to-path: true
    - name: set_version
      run: |
        python3 build/ci_set_version.py
    - name: build
      run: |
        curl -s -O https://nvgt.gg/droidev.zip
        mkdir -p droidev
        cd droidev
        unzip -q ../droidev.zip
        cd ../jni
        ./gradlew assembleRunnerRelease AssembleStubRelease --no-daemon -Pandroid.injected.signing.store.file=android.keystore -Pandroid.injected.signing.store.password=${{secrets.ANDROID_RUNNER_KEYSTORE_PW}} -Pandroid.injected.signing.key.alias=app -Pandroid.injected.signing.key.password="${{secrets.ANDROID_RUNNER_KEYSTORE_PW}}"
        mv build/outputs/apk/runner/release/nvgt-runner-release.apk ../nvgt_$nvgt_version.apk
        cd ..
​      - ​name​: ​Upload App To Artifact
steps:
​        ​uses​: ​actions/upload-artifact@v4
​        ​with​:
​          ​path​: ​"nvgt_$nvgt_version.apk"
​      - ​name​: ​Upload App To Artifact
steps:
​        ​uses​: ​actions/upload-artifact@v4
​        ​with​:
​          ​path​: ​"release/stub/nvgt_android.bin"

  windows_build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: build
      run: |
        pip3 install scons
        choco install -y upx
        curl -s -O https://nvgt.gg/windev.zip
        7z x windev.zip -owindev
        scons -s no_upx=0
        cd release
        tar -czf ../windows_release.tar.gz *
        cd ..
​      - ​name​: ​Upload App To Artifact
steps:
​        ​uses​: ​actions/upload-artifact@v4
​        ​with​:
​          ​path​: ​"windows_release.tar.gz"
